services:
  - type: web
    name: football-blogbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CUSTOM_PROMPT
        sync: false
