services:
  - type: web
    name: football-blog-auto
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  - type: worker
    name: football-blog-manual
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_handler.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
